defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
        title: {{ page.name }}
        layout: index
        description: Something on here...
        omitTitle: false;

layouts_dir: _layouts
