defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
        title: 
        layout: index
        description: {{page.title}} on hitscan.org
        omitTitle: false
        script: 

layouts_dir: _layouts
